FROM python:3.9-slim

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

WORKDIR /app

COPY ./transcendences /app/

COPY ./requirements.txt /app

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

EXPOSE 8000
