# Generated by Django 4.2.16 on 2024-10-13 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='manager',
        ),
    ]
