# Generated by Django 4.2.16 on 2024-10-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_user_user_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
