# Generated by Django 4.2.16 on 2024-10-30 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_loses_user_wins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, default=None, related_name='users', to='user.user'),
        ),
    ]
